### ISSUE TITLE
Doesn't work over https or ssl

### ISSUE THREAD

**Issue by rfinquiron** [jdutheil/nodePHP#3]
It works well with http but Gives error when its run over https.

![image](https://cloud.githubusercontent.com/assets/4939880/9626094/1dfa331a-516c-11e5-9985-6e2b41a9f382.png)

**Comment by bhdrgkz** [comment]
Hi @rfinquiron ,
var http = require( 'http' );   ->   var https = require( 'https' );

**Comment by rfinquiron** [comment]
I got this working with this code

    var opts = {
        key : fs.readFileSync(nodeConfig.serverKeyFile),
	cert : fs.readFileSync(nodeConfig.serverCrtFile),
    };
    var server = https.createServer(opts, app);
